library(openxlsx)
library(tidyverse)
library(janitor)
source("Excel_Format_Params.r")

# @sheets: all sheets from the excel generated by 06_01_Cofdr_Format_Excel.r
format_sig_snp <- function(pheno, sheets)
{
	print(paste(pheno, "start!"))
	dat = sheets[[which(names(sheets)==pheno)]]
	
	# T1.sig_snps
	if(is.null(dat$T1.sig_snps)){
		sig_snps = as.data.frame(matrix(ncol=2, nrow=0))
	} else{
		sig_snps = dat$T1.sig_snps[-1, ] %>% row_to_names(row_number = 1) %>% dplyr::select(SNP)
		sig_snps = as.data.frame(cbind(sig_snps, pheno))
	}	
	colnames(sig_snps) = c("SNP", "comparisons")
	
	# T2.risk_loci
	if(is.null(dat$T2.risk_loci)){
		risk_loci = as.data.frame(matrix(ncol=2, nrow=0))
	} else{
		risk_loci = dat$T2.risk_loci[-1, ] %>% row_to_names(row_number = 1) %>% dplyr::select(rsID)
		risk_loci = as.data.frame(cbind(risk_loci, pheno))	
	}
	colnames(risk_loci) = c("SNP", "comparisons")
		
	# T7.commonLoci_cofdr_gwaspw_hypr
	if(is.null(dat$T7.commonLoci_cofdr_gwaspw_hypr)){
		commonLoci_cofdr_gwaspw_hypr = as.data.frame(matrix(ncol=2, nrow=0))
	} else{
		commonLoci_cofdr_gwaspw_hypr = dat$T7.commonLoci_cofdr_gwaspw_hypr[-1, ] %>% row_to_names(row_number = 1) %>% filter(total_detect==3) %>% dplyr::select(SNP)
		if(nrow(commonLoci_cofdr_gwaspw_hypr)>0){
			commonLoci_cofdr_gwaspw_hypr = as.data.frame(cbind(commonLoci_cofdr_gwaspw_hypr, pheno))		
		} else{
			commonLoci_cofdr_gwaspw_hypr = as.data.frame(matrix(ncol=2, nrow=0))		
		}	
	}	
	colnames(commonLoci_cofdr_gwaspw_hypr) = c("SNP", "comparisons")
	
	# T8.gene_based_cofdr
	if(is.null(dat$T8.gene_based_cofdr)){
		gene_based_cofdr = as.data.frame(matrix(ncol=2, nrow=0))
	} else{
		gene_based_cofdr = dat$T8.gene_based_cofdr[-1, ] %>% row_to_names(row_number = 1) %>% mutate(total_detect=as.numeric(total_detect)) %>% filter(total_detect>=3) %>% dplyr::select(hgnc_symbol)
		if(nrow(gene_based_cofdr)>0){
			gene_based_cofdr = as.data.frame(cbind(unique(gene_based_cofdr), pheno))		
		} else{
			gene_based_cofdr = as.data.frame(matrix(ncol=2, nrow=0))		
		}	
	}	
	colnames(gene_based_cofdr) = c("Gene", "comparisons")
	
	# T9.sig_gene_GSEA
	if(is.null(dat$T9.sig_gene_GSEA)){
		sig_gene_GSEA = as.data.frame(matrix(ncol=2, nrow=0))
	} else{
		sig_gene_GSEA = dat$T9.sig_gene_GSEA[-1, ] %>% row_to_names(row_number = 1) %>% dplyr::select(GeneSet)
		if(nrow(sig_gene_GSEA)>0){
			sig_gene_GSEA = as.data.frame(cbind(unique(sig_gene_GSEA), pheno))		
		} else{
			sig_gene_GSEA = as.data.frame(matrix(ncol=2, nrow=0))		
		}		
	}
	colnames(sig_gene_GSEA) = c("GeneSet", "comparisons")
		
	return(list(sig_snps, risk_loci, commonLoci_cofdr_gwaspw_hypr, gene_based_cofdr, sig_gene_GSEA))
}

Cofdr_Excel_Summary <- function(excel_dir, save_path, multi_cofdr=FALSE)
{		
	paths = list.files(excel_dir, pattern=".xlsx", full.names=TRUE)	
	phenos = stringi::stri_replace_all_regex(basename(paths), pattern=".xlsx", replacement="", vectorize=FALSE)
	
	sheets = pbapply::pblapply(paths, read_all_sheets)	
	names(sheets) = phenos
	res = lapply(phenos, format_sig_snp, sheets=sheets)
	
	# idx: index for "sig_snps, risk_loci, commonLoci_cofdr_gwaspw_hypr, gene_based_cofdr, sig_gene_GSEA"
	# col1: name of the 1st column
	format_Excel <- function(idx, col1)
	{
		print(idx)
		dat = lapply(res, '[[', idx) 
		dat = dat[lapply(dat, nrow)>0] 
		
		if(!identical(dat, list())){
			dat = dat %>% reduce(full_join, by=col1)
			if(ncol(dat)==2){
				dat$N_comparisons = 1
			}else{
				dat$N_comparisons = apply(dat[, -1], 1, function(x) sum(!is.na(x)))
				dat$comparisons = apply(dat[, -c(1,ncol(dat))], 1, paste, collapse = ";")
			}
			dat = dat[, c(col1, "N_comparisons", "comparisons")]
			dat = dat[order(dat$N_comparisons, decreasing=TRUE),]
		} else{
			dat = setNames(as.data.frame(matrix(ncol=3, nrow=1)), c(col1, "N_comparisons", "comparisons"))
		}
			return(dat)
	}

	wb <- createWorkbook()
	addWorksheet(wb, "T1.sig_snps")
	addWorksheet(wb, "T2.risk_loci")
	addWorksheet(wb, "T3.commonLoci_cofdr_gwaspw_hypr")
	addWorksheet(wb, "T4.gene_based_cofdr")
	addWorksheet(wb, "T5.sig_gene_GSEA")
	
	h1 = "Table 1. Significantly colocalized SNPs detected by co-fdr at posterior possibility threshold 0.9 across all pairwise trait comparisons"
	subh1 = 'SNP=rsid of the colocalized SNP; N_comparisons=number of comparisons identifying the "SNP"; comparisons=name of trait comparisons identifying the "SNP"'
	dat1 = format_Excel(1, "SNP")
	format_header(wb, "T1.sig_snps", c(1, 12), h1, header_style)
	format_header(wb, "T1.sig_snps", c(2, 12), subh1, subheader_style)
	format_main(wb, "T1.sig_snps", dat1, title_style, main_style)
	
	h2 = "Table 2. Identification of genomic risk loci across all pairwise trait comparisons"
	subh2 = 'SNP=rsid of the lead SNP in the genomic locus; N_comparisons=number of comparisons identifying the "SNP"; comparisons=name of trait comparisons identifying the "SNP"'
	dat2 = format_Excel(2, "SNP")
	format_header(wb, "T2.risk_loci", c(1, 13), h2, header_style)
	format_header(wb, "T2.risk_loci", c(2, 13), subh2, subheader_style)
	format_main(wb, "T2.risk_loci", dat2, title_style, main_style)
	
	h3 = "Table 3. Significantly colocalized SNPs detected by cofdr, gwas-pw and hyprcoloc across all pairwise trait comparisons"
	subh3 = 'SNP=rsid of the colocalized SNP; N_comparisons=number of comparisons identifying the "SNP"; comparisons=name of trait comparisons identifying the "SNP"'
	dat3 = format_Excel(3, "SNP")
	format_header(wb, "T3.commonLoci_cofdr_gwaspw_hypr", c(1, 12), h3, header_style)
	format_header(wb, "T3.commonLoci_cofdr_gwaspw_hypr", c(2, 12), subh3, subheader_style)
	format_main(wb, "T3.commonLoci_cofdr_gwaspw_hypr", dat3, title_style, main_style)
	
	h4 = "Table 4. Gene-based co-fdr analysis to detect genes associated with both traits using MAGMA, PrediXcan or FUSION across all pairwise trait comparisons"
	subh4 = 'Gene=HGNC symbol of the colocalized gene; N_comparisons=number of comparisons identifying the "Gene"; comparisons=name of trait comparisons identifying the "Gene"'
	dat4 = format_Excel(4, "Gene")
	format_header(wb, "T4.gene_based_cofdr", c(1, 14), h4, header_style)
	format_header(wb, "T4.gene_based_cofdr", c(2, 14), subh4, subheader_style)
	format_main(wb, "T4.gene_based_cofdr", dat4, title_style, main_style)
	
	h5 = "Table 5. Enrichment of prioritized genes in Gene Sets across all pairwise trait comparisons"
	subh5 = 'GeneSet=Name of the colocalized gene set as provided by FUMA; N_comparisons=number of comparisons identifying the "Gene"; comparisons=name of trait comparisons identifying the "Gene"'
	dat5 = format_Excel(5, "GeneSet")
	format_header(wb, "T5.sig_gene_GSEA", c(1, 15), h5, header_style)
	format_header(wb, "T5.sig_gene_GSEA", c(2, 15), subh5, subheader_style)
	format_main(wb, "T5.sig_gene_GSEA", dat5, title_style, main_style)

	saveWorkbook(wb, file = save_path, overwrite = TRUE)
	
	return(save_path)
}


# Cofdr_Excel_Summary(excel_dir="03_cofdr/10_Excel_Summary/Tables/A2/respiratory", save_path="03_cofdr/10_Excel_Summary/Tables/A2/A2_respiratory.xlsx")
# Cofdr_Excel_Summary(excel_dir="03_cofdr/10_Excel_Summary/Tables/B2/respiratory", save_path="03_cofdr/10_Excel_Summary/Tables/B2/B2_respiratory.xlsx")
# Cofdr_Excel_Summary(excel_dir="03_cofdr/10_Excel_Summary/Tables/C2/respiratory", save_path="03_cofdr/10_Excel_Summary/Tables/C2/C2_respiratory.xlsx")


# # A2+B2+C2 vs respiratory
# Cofdr_Excel_Summary(excel_dir=paste0("03_cofdr/10_Excel_Summary/Tables/", c("A2", "B2", "C2"), "/respiratory"), save_path="03_cofdr/10_Excel_Summary/Tables/A2_B2_C2_respiratory.xlsx")